# ===================== Build stage =====================
FROM node:20-alpine AS build
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy file dependency
COPY Backtrack.Notification/package.json Backtrack.Notification/pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY Backtrack.Notification/. .
RUN pnpm run build

# ===================== Runtime stage =====================
FROM node:20-alpine AS final
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY --chown=node:node Backtrack.Notification/package.json Backtrack.Notification/pnpm-lock.yaml ./

RUN pnpm install --prod --frozen-lockfile && \
    pnpm store prune

COPY --from=build --chown=node:node /app/dist ./dist

USER node

CMD ["node", "dist/index.js"]