using Backtrack.Core.Domain.Entities;
using Backtrack.Core.Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NpgsqlTypes;
using Pgvector;
using System.Collections;

namespace Backtrack.Core.Infrastructure.Data.Configurations
{
    public class PostConfiguration : IEntityTypeConfiguration<Post>
    {
        public void Configure(EntityTypeBuilder<Post> builder)
        {
            builder.ToTable("posts");

            builder.HasKey(p => p.Id);

            builder.Property(p => p.Id)
                .HasColumnName("id")
                .IsRequired();

            builder.Property(p => p.PostType)
                .HasColumnName("post_type")
                .HasConversion<string>()
                .IsRequired();

            builder.Property(p => p.Status)
                .HasColumnName("status")
                .HasConversion<string>()
                .HasDefaultValue(Domain.Constants.PostStatus.Active)
                .IsRequired();

            builder.OwnsOne(p => p.Item, owned =>
            {
                owned.Property(i => i.ItemName)
                    .HasColumnName("item_name")
                    .HasMaxLength(500)
                    .IsRequired();

                owned.Property(i => i.Category)
                    .HasColumnName("item_category")
                    .HasConversion<string>()
                    .HasMaxLength(50);

                owned.Property(i => i.Color)
                    .HasColumnName("item_color")
                    .HasMaxLength(100);

                owned.Property(i => i.Brand)
                    .HasColumnName("item_brand")
                    .HasMaxLength(100);

                owned.Property(i => i.Condition)
                    .HasColumnName("item_condition")
                    .HasMaxLength(100);

                owned.Property(i => i.Material)
                    .HasColumnName("item_material")
                    .HasMaxLength(100);

                owned.Property(i => i.Size)
                    .HasColumnName("item_size")
                    .HasMaxLength(100);

                owned.Property(i => i.DistinctiveMarks)
                    .HasColumnName("item_distinctive_marks")
                    .HasMaxLength(500);

                owned.Property(i => i.AdditionalDetails)
                    .HasColumnName("item_additional_details")
                    .HasMaxLength(2000);
            });

            // tsvector full-text search column — auto-generated by PostgreSQL on every insert/update
            // Weights: A = item_name (highest), B = category/brand, C = physical attributes, D = additional_details (lowest)
            builder.Property<NpgsqlTsVector>("ItemSearch")
                .HasColumnName("item_search")
                .HasColumnType("tsvector")
                .HasComputedColumnSql(
                    "setweight(to_tsvector('english', coalesce(item_name, '')),               'A') || " +
                    "setweight(to_tsvector('english', coalesce(item_category, '') || ' ' || coalesce(item_brand, '')), 'B') || " +
                    "setweight(to_tsvector('english', coalesce(item_color, '')     || ' ' || coalesce(item_condition, '') || ' ' || coalesce(item_material, '') || ' ' || coalesce(item_size, '') || ' ' || coalesce(item_distinctive_marks, '')), 'C') || " +
                    "setweight(to_tsvector('english', coalesce(item_additional_details, '')), 'D')",
                    stored: true);

            builder.HasIndex("ItemSearch")
                .HasDatabaseName("ix_posts_item_search")
                .HasMethod("gin");

            builder.Property(p => p.ImageUrls)
                .HasColumnName("image_urls")
                .HasColumnType("text[]")
                .IsRequired();

            builder.Property(p => p.AuthorId)
                .HasColumnName("author_id")
                .HasColumnType("text")
                .IsRequired();

            builder.HasOne(p => p.Author)
                .WithMany()
                .HasForeignKey(p => p.AuthorId)
                .HasConstraintName("fk_posts_author_id_users_id")
                .OnDelete(DeleteBehavior.NoAction);

            builder.HasIndex(p => p.AuthorId)
                .HasDatabaseName("ix_posts_author_id");

            builder.Property(p => p.OrganizationId)
                .HasColumnName("organization_id");

            builder.HasOne(p => p.Organization)
                .WithMany(o => o.Posts)
                .HasForeignKey(p => p.OrganizationId)
                .HasConstraintName("fk_posts_organization_id_organizations_id")
                .OnDelete(DeleteBehavior.SetNull);

            var geoPointToPointConverter = new ValueConverter<GeoPoint, Point>(
                toDb => new Point(toDb.Longitude, toDb.Latitude) { SRID = 4326 },
                fromDb => new GeoPoint(fromDb.Y, fromDb.X)
            );

            var geoPointComparer = new ValueComparer<GeoPoint>(
                (a, b) => a != null && b != null && a.Latitude == b.Latitude && a.Longitude == b.Longitude,
                v => v == null ? 0 : HashCode.Combine(v.Latitude, v.Longitude),
                v => new GeoPoint(v.Latitude, v.Longitude)
            );

            builder.Property(p => p.Location)
                .HasColumnName("location")
                .HasColumnType("geography(point, 4326)")
                .HasConversion(geoPointToPointConverter, geoPointComparer)
                .IsRequired();

            builder.Property(p => p.ExternalPlaceId)
                .HasColumnName("external_place_id")
                .HasMaxLength(500);

            builder.Property(p => p.DisplayAddress)
                .HasColumnName("display_address")
                .HasMaxLength(1000)
                .IsRequired();

            // Vector converter for embeddings
            var embeddingToVectorConverter = new ValueConverter<float[]?, Vector?>(
                toDb => toDb == null ? null : new Vector(toDb),
                fromDb => fromDb == null ? null : fromDb.ToArray()
            );

            var embeddingComparer = new ValueComparer<float[]?>(
                (a, b) =>
                    a == b || (a != null && b != null && a.SequenceEqual(b)),
                v =>
                    v == null ? 0 : StructuralComparisons.StructuralEqualityComparer.GetHashCode(v),
                v =>
                    v == null ? null : v.ToArray()
            );

            builder.Property(p => p.Embedding)
                .HasColumnName("embedding")
                .HasColumnType("vector(1536)")
                .HasConversion(embeddingToVectorConverter, embeddingComparer);

            builder.Property(p => p.ContentHash)
                .HasColumnName("content_hash")
                .HasMaxLength(64)
                .IsRequired();

            builder.Property(p => p.EmbeddingStatus)
                .HasColumnName("embedding_status")
                .HasConversion<string>()
                .IsRequired();

            builder.Property(p => p.PostMatchingStatus)
                .HasColumnName("post_matching_status")
                .HasConversion<string>()
                .IsRequired();

            builder.Property(p => p.EventTime)
                .HasColumnName("event_time")
                .IsRequired();

            builder.Property(p => p.CreatedAt)
                .HasColumnName("created_at")
                .IsRequired();

            builder.Property(p => p.UpdatedAt)
                .HasColumnName("updated_at");

            builder.Property(p => p.DeletedAt)
                .HasColumnName("deleted_at");

            // Indexes
            builder.HasIndex(p => p.PostType)
                .HasDatabaseName("ix_posts_post_type");

            builder.HasIndex(p => p.EventTime)
                .HasDatabaseName("ix_posts_event_time");

            // Spatial index for location using GIST
            builder.HasIndex(p => p.Location)
                .HasDatabaseName("ix_posts_location")
                .HasMethod("gist");

            // Vector index for embedding using HNSW for efficient similarity search
            builder.HasIndex(p => p.Embedding)
                .HasDatabaseName("ix_posts_embedding")
                .HasMethod("hnsw")
                .HasOperators("vector_cosine_ops");

            // Global query filter for soft delete
            builder.HasQueryFilter(p => p.DeletedAt == null);
        }
    }
}
