// <auto-generated />
using System;
using Backtrack.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Backtrack.Core.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319062642_AddLlmAssessmentToPostMatch")]
    partial class AddLlmAssessmentToPostMatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.JoinInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiredTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_time");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hash_code");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_join_invitations_email");

                    b.HasIndex("HashCode")
                        .IsUnique()
                        .HasDatabaseName("ix_join_invitations_hash_code");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("OrganizationId");

                    b.ToTable("join_invitations", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_org_user")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("display_address");

                    b.Property<string>("ExternalPlaceId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_place_id");

                    b.Property<string>("IndustryType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("industry_type");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_identification_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.OrganizationInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DistinctiveMarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("distinctive_marks");

                    b.Property<string[]>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_name");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("LoggedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logged_by_id");

                    b.Property<Vector>("MultimodalEmbedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("multimodal_embedding");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_location");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LoggedById")
                        .HasDatabaseName("ix_org_inventories_logged_by_id");

                    b.HasIndex("MultimodalEmbedding")
                        .HasDatabaseName("ix_org_inventories_multimodal_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MultimodalEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("MultimodalEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_org_inventories_org_id");

                    b.ToTable("org_inventories", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("ContentEmbeddingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_embedding_status");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("display_address");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("ExternalPlaceId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_place_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_name");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(point, 4326)")
                        .HasColumnName("location");

                    b.Property<Vector>("MultimodalEmbedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("multimodal_embedding");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostMatchingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_matching_status");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_posts_author_id");

                    b.HasIndex("EventTime")
                        .HasDatabaseName("ix_posts_event_time");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_posts_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MultimodalEmbedding")
                        .HasDatabaseName("ix_posts_multimodal_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MultimodalEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("MultimodalEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PostType")
                        .HasDatabaseName("ix_posts_post_type");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Base64Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base64_data");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_images_post_id");

                    b.ToTable("post_images", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.PostMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssessmentSummary")
                        .HasColumnType("text")
                        .HasColumnName("assessment_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<float>("DistanceMeters")
                        .HasColumnType("real")
                        .HasColumnName("distance_meters");

                    b.Property<Guid>("FoundPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("found_post_id");

                    b.Property<string[]>("KeyDifferences")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("key_differences")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string[]>("KeyMatches")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("key_matches")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("LostPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("lost_post_id");

                    b.Property<float>("MatchScore")
                        .HasColumnType("real")
                        .HasColumnName("match_score");

                    b.Property<int?>("MatchingLevel")
                        .HasColumnType("integer")
                        .HasColumnName("matching_level");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FoundPostId")
                        .HasDatabaseName("ix_post_matches_found_post_id");

                    b.HasIndex("LostPostId")
                        .HasDatabaseName("ix_post_matches_lost_post_id");

                    b.HasIndex("FoundPostId", "LostPostId")
                        .IsUnique()
                        .HasDatabaseName("ux_post_matches_found_lost_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("post_matches", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GlobalRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("global_role");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool>("ShowEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_email");

                    b.Property<bool>("ShowPhone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.JoinInvitation", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.User", "InviterUser")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_join_invitations_invited_by");

                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_join_invitations_organization_id");

                    b.Navigation("InviterUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Membership", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_organization_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.OrganizationInventory", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.User", "LoggedBy")
                        .WithMany()
                        .HasForeignKey("LoggedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_org_inventories_logged_by_id_users_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_inventories_org_id_organizations_id");

                    b.Navigation("LoggedBy");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Post", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_posts_author_id_users_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany("Posts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_posts_organization_id_organizations_id");

                    b.Navigation("Author");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_images_post_id_posts_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.PostMatch", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "FoundPost")
                        .WithMany()
                        .HasForeignKey("FoundPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_matches_found_post_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "LostPost")
                        .WithMany()
                        .HasForeignKey("LostPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_matches_lost_post_id");

                    b.Navigation("FoundPost");

                    b.Navigation("LostPost");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Post", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
