// <auto-generated />
using System;
using System.Collections.Generic;
using Backtrack.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace Backtrack.Core.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405090553_AddC2CReturnReportOrgReturnReportTable")]
    partial class AddC2CReturnReportOrgReturnReportTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.C2CReturnReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FinderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("finder_id");

                    b.Property<Guid?>("FinderPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("finder_post_id");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("OwnerPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FinderId")
                        .HasDatabaseName("ix_c2c_return_reports_finder_id");

                    b.HasIndex("FinderPostId")
                        .HasDatabaseName("ix_c2c_return_reports_finder_post_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_c2c_return_reports_owner_id");

                    b.HasIndex("OwnerPostId")
                        .HasDatabaseName("ix_c2c_return_reports_owner_post_id");

                    b.ToTable("c2c_return_reports", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.FinderContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("national_id");

                    b.Property<string>("OrgMemberId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_member_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_finder_contacts_inventory_id");

                    b.ToTable("finder_contacts", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.JoinInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiredTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_time");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hash_code");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_join_invitations_email");

                    b.HasIndex("HashCode")
                        .IsUnique()
                        .HasDatabaseName("ix_join_invitations_hash_code");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("OrganizationId");

                    b.ToTable("join_invitations", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_org_user")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.OrgReturnReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("OwnerRequiredInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("owner_required_info");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("staff_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_org_return_reports_org_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_org_return_reports_post_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_org_return_reports_staff_id");

                    b.ToTable("org_return_reports", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("business_hours");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("display_address");

                    b.Property<string>("ExternalPlaceId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_place_id");

                    b.Property<string>("IndustryType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("industry_type");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("LocationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("location_note");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string[]>("RequiredFinderContractFields")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("required_finder_contract_fields");

                    b.Property<string[]>("RequiredOwnerContractFields")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("required_owner_contract_fields");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_identification_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.OrganizationInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DistinctiveMarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("distinctive_marks");

                    b.Property<string>("HandoverStaffId")
                        .HasColumnType("text")
                        .HasColumnName("handover_staff_id");

                    b.Property<string[]>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_name");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("LoggedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logged_by_id");

                    b.Property<Vector>("MultimodalEmbedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("multimodal_embedding");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("ReceiverStaffId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_location");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HandoverStaffId");

                    b.HasIndex("LoggedById")
                        .HasDatabaseName("ix_org_inventories_logged_by_id");

                    b.HasIndex("MultimodalEmbedding")
                        .HasDatabaseName("ix_org_inventories_multimodal_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MultimodalEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("MultimodalEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_org_inventories_org_id");

                    b.HasIndex("ReceiverStaffId");

                    b.ToTable("org_inventories", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("display_address");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("embedding_status");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<string>("ExternalPlaceId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_place_id");

                    b.Property<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<NpgsqlTsVector>("ItemSearch")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("item_search")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(item_name, '')),               'A') || setweight(to_tsvector('english', coalesce(item_category, '') || ' ' || coalesce(item_brand, '')), 'B') || setweight(to_tsvector('english', coalesce(item_color, '')     || ' ' || coalesce(item_condition, '') || ' ' || coalesce(item_material, '') || ' ' || coalesce(item_size, '') || ' ' || coalesce(item_distinctive_marks, '')), 'C') || setweight(to_tsvector('english', coalesce(item_additional_details, '')), 'D')", true);

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(point, 4326)")
                        .HasColumnName("location");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostMatchingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_matching_status");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_posts_author_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_posts_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("EventTime")
                        .HasDatabaseName("ix_posts_event_time");

                    b.HasIndex("ItemSearch")
                        .HasDatabaseName("ix_posts_item_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ItemSearch"), "gin");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_posts_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PostType")
                        .HasDatabaseName("ix_posts_post_type");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.PostMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssessmentSummary")
                        .HasColumnType("text")
                        .HasColumnName("assessment_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriteriaAssessment")
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria_json");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DescriptionScore")
                        .HasColumnType("integer")
                        .HasColumnName("description_score");

                    b.Property<float>("DistanceMeters")
                        .HasColumnType("real")
                        .HasColumnName("distance_meters");

                    b.Property<Guid>("FoundPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("found_post_id");

                    b.Property<bool>("IsAssessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_assessed");

                    b.Property<int>("LocationScore")
                        .HasColumnType("integer")
                        .HasColumnName("location_score");

                    b.Property<Guid>("LostPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("lost_post_id");

                    b.Property<float>("MatchScore")
                        .HasColumnType("real")
                        .HasColumnName("match_score");

                    b.Property<string>("MatchingLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matching_level");

                    b.Property<int>("TimeWindowScore")
                        .HasColumnType("integer")
                        .HasColumnName("time_window_score");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VisualScore")
                        .HasColumnType("integer")
                        .HasColumnName("visual_score");

                    b.HasKey("Id");

                    b.HasIndex("FoundPostId")
                        .HasDatabaseName("ix_post_matches_found_post_id");

                    b.HasIndex("LostPostId")
                        .HasDatabaseName("ix_post_matches_lost_post_id");

                    b.HasIndex("FoundPostId", "LostPostId")
                        .IsUnique()
                        .HasDatabaseName("ux_post_matches_found_lost_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("post_matches", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GlobalRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("global_role");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool>("ShowEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_email");

                    b.Property<bool>("ShowPhone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.C2CReturnReport", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.User", "Finder")
                        .WithMany()
                        .HasForeignKey("FinderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_c2c_return_reports_finder_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "FinderPost")
                        .WithMany()
                        .HasForeignKey("FinderPostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_c2c_return_reports_finder_post_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_c2c_return_reports_owner_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "OwnerPost")
                        .WithMany()
                        .HasForeignKey("OwnerPostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_c2c_return_reports_owner_post_id");

                    b.Navigation("Finder");

                    b.Navigation("FinderPost");

                    b.Navigation("Owner");

                    b.Navigation("OwnerPost");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.FinderContact", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.OrganizationInventory", "Inventory")
                        .WithOne("FinderContact")
                        .HasForeignKey("Backtrack.Core.Domain.Entities.FinderContact", "InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finder_contacts_inventory_id_org_inventories_id");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.JoinInvitation", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.User", "InviterUser")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_join_invitations_invited_by");

                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_join_invitations_organization_id");

                    b.Navigation("InviterUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Membership", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_organization_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.OrgReturnReport", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_return_reports_org_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_return_reports_post_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_return_reports_staff_id");

                    b.Navigation("Organization");

                    b.Navigation("Post");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.OrganizationInventory", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.User", "HandoverStaff")
                        .WithMany()
                        .HasForeignKey("HandoverStaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_org_inventories_handover_staff_id_users_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.User", "LoggedBy")
                        .WithMany()
                        .HasForeignKey("LoggedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_org_inventories_logged_by_id_users_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_inventories_org_id_organizations_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.User", "ReceiverStaff")
                        .WithMany()
                        .HasForeignKey("ReceiverStaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_org_inventories_receiver_staff_id_users_id");

                    b.Navigation("HandoverStaff");

                    b.Navigation("LoggedBy");

                    b.Navigation("Organization");

                    b.Navigation("ReceiverStaff");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Post", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_posts_author_id_users_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Organization", "Organization")
                        .WithMany("Posts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_posts_organization_id_organizations_id");

                    b.OwnsOne("Backtrack.Core.Domain.ValueObjects.PostItem", "Item", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalDetails")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("item_additional_details");

                            b1.Property<string>("Brand")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("item_brand");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("item_category");

                            b1.Property<string>("Color")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("item_color");

                            b1.Property<string>("Condition")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("item_condition");

                            b1.Property<string>("DistinctiveMarks")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("item_distinctive_marks");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("item_name");

                            b1.Property<string>("Material")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("item_material");

                            b1.Property<string>("Size")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("item_size");

                            b1.HasKey("PostId");

                            b1.ToTable("posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("Author");

                    b.Navigation("Item")
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.PostMatch", b =>
                {
                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "FoundPost")
                        .WithMany()
                        .HasForeignKey("FoundPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_matches_found_post_id");

                    b.HasOne("Backtrack.Core.Domain.Entities.Post", "LostPost")
                        .WithMany()
                        .HasForeignKey("LostPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_matches_lost_post_id");

                    b.Navigation("FoundPost");

                    b.Navigation("LostPost");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.OrganizationInventory", b =>
                {
                    b.Navigation("FinderContact");
                });

            modelBuilder.Entity("Backtrack.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
